"""Fill the memo, evaluation page, data page, and README measured blocks."""

from __future__ import annotations

from pathlib import Path

from _lib import read_json

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
FPR = HERE / "benign_fpr" / "results"
LAT = HERE / "screening_latency" / "results"
SPLIT = HERE / "split_order_sim" / "results"


def _md(path: Path) -> str:
    return path.read_text(encoding="utf-8").strip()


def _table_from_md(path: Path) -> str:
    lines = [line for line in _md(path).splitlines() if line.startswith("|")]
    return "\n".join(lines)


def render_memo() -> str:
    template = (HERE / "templates" / "research-memo.md").read_text(encoding="utf-8")
    fpr = read_json(FPR / "results.json")
    lat = read_json(LAT / "results.json")
    split = read_json(SPLIT / "results.json")
    cost_lines = [
        f"- Benign queries scored: {fpr['n_queries']}",
        f"- Mean identity vs benign panel: {fpr['mean_identity']:.3f}",
        f"- Default threshold {fpr['default_threshold']:.2f} FPR: {fpr['default_fpr']:.3f}",
        f"- Indexed backend total on the latency grid: {lat['indexed_total_seconds']:.4f}s",
        f"- Naive backend total on the latency grid: {lat['naive_total_seconds']:.4f}s",
        "- BLAST / DIAMOND / HMM RTT: unmeasured",
        "- USD / order: unmeasured (no API)",
        f"- Split-order R001 reconstructed fraction: {split['r001_reconstructed_fraction']:.3f}",
    ]
    filled = (
        template.replace("{{FPR_N}}", str(fpr["n_queries"]))
        .replace("{{FPR_TABLE}}", _table_from_md(FPR / "results.md"))
        .replace("{{FPR_DECISION}}", str(fpr["decision"]))
        .replace("{{FPR_SUMMARY}}", _md(FPR / "results.md").split("##")[0].strip())
        .replace(
            "{{LAT_SUMMARY}}",
            f"Faster backend = {lat['faster_backend']}. "
            f"Indexed {lat['indexed_total_seconds']:.4f}s vs "
            f"naive {lat['naive_total_seconds']:.4f}s.",
        )
        .replace("{{LAT_DECISION}}", str(lat["decision"]))
        .replace(
            "{{SPLIT_SUMMARY}}",
            f"R001 detected={split['r001_detected']}. "
            f"Control FP={split['control_false_positives']}/{split['n_controls']}.",
        )
        .replace("{{SPLIT_DECISION}}", str(split["decision"]))
        .replace("{{COST_MODEL}}", "\n".join(cost_lines))
    )
    return filled


def render_eval() -> str:
    return (
        "# Evaluation (Phase 0 baseline)\n\n"
        "Regenerated by `make eval` / `make research`. "
        "SOC TPR numbers do not exist and must not be faked. "
        "The benign FPR below is the baseline a later backend must keep.\n\n"
        f"{_md(FPR / 'results.md')}\n\n"
        f"{_md(LAT / 'results.md')}\n\n"
        f"{_md(SPLIT / 'results.md')}\n"
    )


def render_data() -> str:
    fpr = read_json(FPR / "results.json")
    split = read_json(SPLIT / "results.json")
    return (
        "# Data\n\n"
        "Phase 0 does not download BLAST databases or sequences of concern. "
        "The committed objects are benign by construction:\n\n"
        "- `data/sample/plasmid.fa` — designed plasmid-backbone-style fragment\n"
        "- `data/sample/housekeep.fa` — designed human housekeeping-style ORF\n"
        "- `data/sample/near-miss.fa` — designed homolog of a benign E. coli-like ORF\n"
        "- `data/sample/too-short.fa` — 20 nt, below the 50 nt gate\n"
        "- `data/sample/split-orders/` — five overlapping fragments of one benign gene\n"
        f"- `research/phase0/benign_fpr/probe_set/benign_queries.fa` — "
        f"{fpr['n_queries']} designed benign queries\n"
        f"- `research/phase0/split_order_sim/probe_set/orders.json` — "
        f"R001 plus {split['n_controls']} control requesters\n\n"
        "No hazardous sequences. No customer-identifiable orders. License notes "
        "are in `docs/phase-0/research-memo.md` §3.\n"
    )


def _replace_block(text: str, begin: str, end: str, body: str) -> str:
    start = text.index(begin) + len(begin)
    stop = text.index(end)
    return text[:start] + "\n\n" + body.strip() + "\n\n" + text[stop:]


def patch_readme() -> None:
    readme_path = ROOT / "README.md"
    text = readme_path.read_text(encoding="utf-8")
    fpr = read_json(FPR / "results.json")
    lat = read_json(LAT / "results.json")
    split = read_json(SPLIT / "results.json")
    body = (
        "| System | Metric | n | Notes |\n"
        "| --- | --- | --- | --- |\n"
        f"| Identity ≥ {fpr['default_threshold']:.2f} (Phase 0 default) | "
        f"FPR {fpr['default_fpr']:.3f} | {fpr['n_queries']} | "
        f"Benign panel as stand-in hit list |\n"
        f"| Recommended threshold {fpr['recommended_threshold']:.2f} | "
        f"FPR {fpr['recommended_fpr']:.3f} | {fpr['n_queries']} | "
        f"Lowest T with FPR ≤ {fpr['target_fpr']:.2f} |\n"
        f"| Local homology backend | faster={lat['faster_backend']} | "
        f"grid | BLAST/DIAMOND/HMM deferred; RTT unmeasured |\n"
        f"| Split-order graph | R001 detected={split['r001_detected']} | "
        f"{split['n_requesters']} requesters | "
        f"control FP {split['control_false_positives']}/{split['n_controls']} |\n"
        "| SOC TPR | unmeasured | — | No hazard sequences committed |\n"
    )
    text = _replace_block(text, "<!-- EVAL_TABLE_BEGIN -->", "<!-- EVAL_TABLE_END -->", body)
    readme_path.write_text(text, encoding="utf-8")


def main() -> None:
    memo = render_memo()
    memo_path = ROOT / "docs" / "phase-0" / "research-memo.md"
    memo_path.parent.mkdir(parents=True, exist_ok=True)
    memo_path.write_text(memo, encoding="utf-8")
    (ROOT / "docs" / "EVALUATION.md").write_text(render_eval(), encoding="utf-8")
    (ROOT / "docs" / "DATA.md").write_text(render_data(), encoding="utf-8")
    if (ROOT / "README.md").exists():
        patch_readme()
    print("wrote memo, EVALUATION.md, DATA.md, and README results")


if __name__ == "__main__":
    main()
